# coding: utf-8 
# Project Pendu in ruby for coding club
# Epitech TEK-01
# Cerfio

#ASCII-ART
def image_display(vie)
  if (vie == 9)
    puts("#####################")
  end
  if (vie == 8)
    print("     |\n")
    print("     |\n")
    print("     |\n")
    print("     |\n")
    print("     |\n")
    print("     |\n")
    print("     |\n")
    print("    /|\\\n")
    print("   / | \\\n")
    print("#####################\n")
  end
  if (vie == 7)
    printf("\n     __________\n")
    print("     | //\n")
    print("     |//\n")
    print("     |/\n")
    print("     |\n")
    print("     |\n")
    print("     |\n")
    print("     |\n")
    print("    /|\\\n")
    print("   / | \\\n")
    print("#####################\n")
  end
  if (vie == 6)
    print("\n     __________\n")
    print("     | //      |\n")
    print("     |//       |\n")
    print("     |/\n")
    print("     | \n")
    print("     |\n")
    print("     |\n")
    print("     |\n")
    print("    /|\\\n")
    print("   / | \\\n")
    print("#####################\n")
  end
  if (vie == 5)
    print("\n     __________\n")
    print("     | //      |\n")
    print("     |//       |\n")
    print("     |/       (_)\n")
    print("     |\n")
    print("     |\n")
    print("     |\n")
    print("     |\n")
    print("    /|\\\n")
    print("   / | \\\n")
    print("#####################\n")
  end
 if (vie == 4)
    print("\n     __________\n")
    print("     | //      |\n")
    print("     |//       |\n")
    print("     |/       (_)\n")
    print("     |         |\n")
    print("     |         |\n")
    print("     |         |\n")
    print("     |\n")
    print("    /|\\\n")
    print("   / | \\\n")
    print("#####################\n")
  end
  if (vie == 3)
    print("\n     __________\n")
    print("     | //      |\n")
    print("     |//       |\n")
    print("     |/       (_)\n")
    print("     |         |\n")
    print("     |        /|\n")
    print("     |         |\n")
    print("     |\n")
    print("    /|\\\n")
    print("   / | \\\n")
    print("#####################\n")
  end
  if (vie == 2)
    print("\n     __________\n")
    print("     | //      |\n")
    print("     |//       |\n")
    print("     |/       (_)\n")
    print("     |         |\n")
    print("     |        /|\\\n")
    print("     |         |\n")
    print("     |\n")
    print("    /|\\\n")
    print("   / | \\\n")
    print("#####################\n")
  end
  if (vie == 1)
    print("\n     __________\n")
    print("     | //      |\n")
    print("     |//       |\n")
    print("     |/       (_)\n")
    print("     |         |\n")
    print("     |        /|\\\n")
    print("     |         |\n")
    print("     |        /\n")
    print("    /|\\\n")
    print("   / | \\\n")
    print("#####################\n")
  end
  if (vie == 0)
    print("\n     __________\n")
    print("     | //      |\n")
    print("     |//       |\n")
    print("     |/       (_)\n")
    print("     |         |\n")
    print("     |        /|\\\n")
    print("     |         |\n")
    print("     |        / \\\n")
    print("    /|\\\n")
    print("   / | \\\n")
    print("#####################\n")
  end
end

